#!/bin/bash
#
# GDFDL - A Development Framework for Debian live-build
# Cleanup GRE with ISO file deletion
#
# Copyright (c) 2012-2013, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GDFDL file for details.
#

source /conf
[ -f /conf-custom ] && source /conf-custom

# Show help message
#
if [[ $1 == "--help" || $1 == "-h" || $1 == "help" ]];
then
	echo "
    ${GDFDL_BRANDNAME^^} BUILD ENVIRONMENT
    Usage: `basename "$0"` [OPTION]
	
    Cleanup build environment including ISO files.

    Options:
      --force-cache            Also remove locally cached installation files
	                           from distribution.
"
	exit 0
fi

# do normal cleanup first
${GDFDL_SCRIPTS}/clean

echo -n "Cleaning up build artifacts and caches ... "
rm -rf /iso/*
[[ $1 == "--force-cache" ]] && rm -rf ${GDFDL_DIR}/cache
echo "ok"
