#!/bin/bash
#
# Post-Installation setup tasks
#

### BEGIN INIT INFO
# Provides:          gdfdl-init
# Required-Start:    
# Required-Stop:
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Do initial task for first startup
# Description:       
### END INIT INFO

# General settings
source /gdfdl.conf
[ -f /gdfdl-custom.conf ] && source /gdfdl-custom.conf
set -e

##
# Don't change this file directly.
# Add your custom tasks in separate file called 'gdfdl-custom-init'
# It will be included here automatically.
##

case "$1" in
	start)
		echo -e "Preparing for 1st start ...\n"

		# Update login screen texts
		[ -f /etc/init.d/gdfdl-custom-prompt ] && mv -f /etc/init.d/gdfdl-custom-prompt /etc/init.d/gdfdl-prompt
		sed -i 's/##GDFDL_BRANDNAME##/${GDFDL_BRANDNAME^^}/' /etc/init.d/gdfdl-prompt
		sed -i 's/##GDFDL_BRANDINFO##/${GDFDL_BRANDINFO}/' /etc/init.d/gdfdl-prompt

		# self destruction
		#
		rm -rf /gdfdl.conf
		rm -rf /etc/init.d/gdfdl-init; update-rc.d gdfdl-init remove
		;;

	stop)
		# nothing to do
		;;

	*)
		echo "Undefined usage."
		exit 3
		;;

esac
