#!/bin/bash -e
#

SELF="`readlink -f $0`"
GDFDL_INSTALLER_BASEDIR_CI_00="`dirname ${SELF}`"
GDFDL_INSTALLER_BASEDIR_CI="`dirname ${GDFDL_INSTALLER_BASEDIR_CI_00}`"
GDFDL_INSTALLER_BASEDIR="`dirname ${GDFDL_INSTALLER_BASEDIR_CI}`"
mkdir "${GDFDL_INSTALLER_BASEDIR}/.ci"
cd "${GDFDL_INSTALLER_BASEDIR}/.ci"

GDFDL_BRANCH=""

GDFDL_INSTALLTYPE="ci" bash -ex "${GDFDL_INSTALLER_BASEDIR}/gdfdl-scripts/gdfdl-installer" "${GDFDL_BRANCH}" "${GDFDL_INSTALLER_BASEDIR}" "${GDFDL_INSTALLER_BASEDIR}"
