#!/bin/sh
#
# GDFDL - A Development Framework for Debian live-build
# live-build auto build script
#
# Copyright (c) 2012, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GDFDL file for details.
#

##
# Don't change this file directly.
# Add your custom tasks in separate file called 'build-custom'
# It will be included here automatically.
##

SELF="`readlink -f $0`"

if [ -f `dirname ${SELF}`/build-custom ];
then
	. `dirname ${SELF}`/build-custom
else
	lb build noauto "${@}" 2>&1
fi
