#!/bin/sh
#
# GDFDL - A Development Framework for Debian live-build
# live-build auto config script
#
# Copyright (c) 2012, Julian Pawlowski <jp@jps-networks.eu>
# See LICENSE.GDFDL file for details.
#

##
# Don't change this file directly.
# Add your custom tasks in separate file called 'config-custom'
# It will be included here automatically.
##

SELF="`readlink -f $0`"
GDFDL_BASEDIR_AUTO="`dirname ${SELF}`"

source "${GDFDL_BASEDIR_AUTO}"/../gdfdl.conf
[ -f "${GDFDL_BASEDIR_AUTO}"/../gdfdl-custom.conf ] && source "${GDFDL_BASEDIR_AUTO}"/../gdfdl-custom.conf

if [ -f "${GDFDL_BASEDIR_AUTO}"/config-custom ];
then
	. "${GDFDL_BASEDIR_AUTO}"/config-custom
else
	lb config noauto \
		--apt apt \
		--apt-recommends disabled \
		--architecture i386 \
		--bootstrap-flavour minimal \
		--chroot-filesystem squashfs \
		--debian-installer live \
		--hostname gdfdl-live \
		--iso-application "Debian Live" \
		--iso-preparer "Git Development Framework for Debian live-build" \
		--iso-volume "GDFDL" \
		--language en \
		--linux-flavours 686 \
		--memtest none \
		--packages-lists minimal \
		--syslinux-timeout 10 \
		--win32-loader disabled \
		"${@}"
fi
